version: 3.9
services:
  api:
    depends_on:
      - db
    image:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    networks:
      - api-network
      - db-network
networks:
  api-network:
  db-network:
