"""added nullable false

Revision ID: 515bae856879
Revises: 36346a3e0539
Create Date: 2022-04-19 18:54:10.659591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515bae856879'
down_revision = '36346a3e0539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
